# remote_theme: pages-themes/architect@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
remote_theme: pages-themes/hacker@v0.2.0
# theme: Leap day
# theme: Merlot
# theme: Midnight
# theme: Minima
# theme: Minimal
# theme: Modernist
# theme: Slate
# theme: Tactile
# theme: Time machine
