# remote_theme: pages-themes/architect@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/leap-day@v0.2.0
#remote_theme: pages-themes/merlot@v0.2.0
remote_theme: pages-themes/midnight@v0.2.0
theme: Minima
# remote_theme: pages-themes/minimal@v0.2.0
# theme: Modernist
# theme: Slate
# theme: Tactile
# theme: Time machine
